namespace Atis.SqlExpressionEngine.SqlExpressions
{
    public enum SqlExpressionType
    {
        Custom,
        Table,
        DerivedTable,
        StandaloneSelect,
        DataSourceColumn,
        Add,
        Subtract,
        Multiply,
        Divide,
        Modulus,
        AndAlso,
        OrElse,
        LessThan,
        LessThanOrEqual,
        GreaterThan,
        GreaterThanOrEqual,
        Equal,
        NotEqual,
        Coalesce,
        Select,
        CteReference,
        CteDataSource,
        JoinDataSource,
        Literal,
        Parameter,
        Alias,
        StringFunction,
        FunctionCall,
        DefaultIfEmpty,
        SelectColumnCollection,
        FromDataSource,
        WhereClause,
        HavingClause,
        OrderByClause,
        Union,
        Conditional,
        Exists,
        Like,
        LikeStartsWith,
        LikeEndsWith,
        // A LIKE whose pattern is used verbatim - the caller supplies the wildcards.
        LikePattern,
        /// <summary>
        ///     One LIKE per element of a collection, OR-ed together. The decoration lives in a property
        ///     here, because the node type is spent saying "this repeats".
        /// </summary>
        LikeAny,
        Collection,
        UnwrappableDerivedTable,
        DateAdd,
        DateSubtract,
        Cast,
        DatePart,
        InValues,
        OptionalPredicate,
        Negate,
        Not,
        Update,
        DataManipulationDerivedTable,
        Delete,
        Comment,
        Queryable,
        Fragment,
        DataSourceQueryShape,
        MemberInit,
        QueryShapeMember,
        Insert,
        InsertInto,
        NewGuid,
        OutputColumn,
    }
}
